name: Docker Image CI

on:
  push:
    branches: [ "back" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login to DockerHub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t fastapi . 
    - name: Pusth to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/fastapi-ci-cd-pipeline:latest
