name: Docker Image CI

on:
  push:
    branches: [ "back" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build -t fastapi . 
    - name: Pusth to Docker Hub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/fastapi-ci-cd-pipeline:latest
