name: Docker Image CI

on:
  push:
    branches: [ "back" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/fastapi-ci-cd-pipeline ./backend 
    - name: Pusth to Docker Hub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/fastapi-ci-cd-pipeline:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      working-directory: /home/ubuntu/backend
      run: sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/fastapi-ci-cd-pipeline:latest
    - name: Delete Old docker container
      working-directory: /home/ubuntu/backend
      run: sudo docker rm -f backend-container || true
    - name: Run Docker Container
      working-directory: /home/ubuntu/backend
      run: sudo docker run -d -p 8000:8000 --name backend-container ${{secrets.DOCKERHUB_USERNAME}}/fastapi-ci-cd-pipeline:latest
